### ISSUE TITLE
How is Player different from GA perspective? 

### ISSUE THREAD

**Issue by AbeYelemessov** [easably/platform-player-extension#140]
@Vlad-CSA , this is a less formal task, but we need your expert opinion on the structural matter. 
We are planning to make a single Google Analytics Property for all our products with one UA identification number. 
We need to document your comment regarding this plan for discussion purposes.

**Comment by Vlad-CSA** [comment]
The player differs from our other products - tutor and extension in that it is a separate application. And we don’t have the opportunity to build a continuous journey of the user through our applications, because cookies from the browser are not transferred in any way to the player and vice versa, that is, the application is isolated from the point of view of GA
