### ISSUE TITLE
[5h]player download stops after 30% of the installing 

### ISSUE THREAD

**Issue by KatyaLogosh** [easably/platform-player-extension#193]
Description:
When a user install player for the first time- the window of downloading displays that after 30% of installing, the video stops dowloading 
Expected result: the video downloads without problems.
Conditions:
You are trying to back up your files, and there is a corruption.
You are trying to install a Windows operating system and the System Reserved Partition is corrupted.
Corrupt registry or policy entries are interfering with the Windows Update process.
There were some problems installing updates, and the system will attempt to try again later.

![image](https://user-images.githubusercontent.com/63041847/85290513-ccfba680-b4a1-11ea-9e96-c74ca4601f52.png)
![image](https://user-images.githubusercontent.com/63041847/85291592-5c558980-b4a3-11ea-8176-d693918da4bf.png)

**Comment by sergeifedorenko** [comment]
@AbeYelemessov @Alexx-13 please check the new build and install https://docs.microsoft.com/en-us/sysinternals/downloads/process-explorer

**Comment by Alexx-13** [comment]
This bug was solved only with 'soft organizer' app. (https://www.chemtable.com/ru/soft-organizer.htm) Due to investigation, it is clear that, old versions perhaps, or current version too, in some case, did not deleats fully by client, there are some leads in the system which are blocking the process of instalation
